### PR TITLE
more tests

### PR DESCRIPTION
**Pull request by ericrini**

### CODE REVIEW

**Comment by robot-muscle** [comment]
BroBot Says:
```
undefined/bin/sh: ./ci-build.sh: No such file or directory


```

**Comment by robot-muscle** [comment]
Build passed. +1

**Comment by robot-muscle** [comment]
Build passed. +1

**Comment by robot-muscle** [comment]
Build Passed +1

**Comment by robot-muscle** [comment]
Build Passed +1

**Comment by robot-muscle** [comment]
Build Passed +1

**Comment by robot-muscle** [comment]
```%s%s%s```

**Comment by robot-muscle** [comment]
```%s%s%s```

**Comment by robot-muscle** [comment]
```%s%s%s```

**Comment by robot-muscle** [comment]
```
RUNNING BUILD NOW

```

**Comment by robot-muscle** [comment]
Build Passed +1

**Comment by robot-muscle** [comment]
Build Passed +1

**Comment by robot-muscle** [comment]
Build Passed +1

**Comment by ijoin-admin** [comment]
Build Passed +1

**Pull request closed without merging**
